### ISSUE TITLE
Formatter breaking dependencies specified as strings (PEP 508)

### ISSUE THREAD

**Issue by onyx-and-iris** [Shellomo/vscode_ext_enhanced_toml#3]
Hi, great efforts with this plugin.

If I generate a pyproject.toml with poetry 2, for example:

```toml
[project]
name = "test-toml-format"
version = "0.1.0"
description = ""
authors = [
    {name = "onyx-and-iris",email = "code@onyxandiris.online"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "keyboard (>=0.13.5,<0.14.0)",
    "obsws-python (>=1.7.1,<2.0.0)",
    "slobs-websocket @ git+https://git@github.com/onyx-and-iris/slobs_websocket",
    "tomli (>=2.2.1,<3.0.0) ; python_version < \"3.11\"",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
```

And then I run this plugins formatter the result becomes:

```toml
[project]
name = "test-toml-format"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
"keyboard (> = 0.13.5,<0.14.0)",
"obsws-python (> = 1.7.1,<2.0.0)",
"slobs-websocket @ git+https://git@github.com/onyx-and-iris/slobs_websocket",
"tomli (> = 2.2.1,<3.0.0) ; python_version < \"3.11\""
]


[[project.authors]]
name = "onyx-and-iris"
email = "code@onyxandiris.online"


[build-system]
requires = [ "poetry-core>=2.0.0,<3.0.0" ]
build-backend = "poetry.core.masonry.api"
```

If I then run `poetry install` I get the following error:
```
The requirement is invalid: Unexpected character at column 15

keyboard (> = 0.13.5,<0.14.0)
```

The same issue occurs in this example:

`"slobs-websocket @ git+https://git@github.com/onyx-and-iris/slobs_websocket@v0.1.4#egg=slobs_websocket"`

which becomes:

`"slobs-websocket @ git+https://git@github.com/onyx-and-iris/slobs_websocket@v0.1.4#egg = slobs_websocket"`

So I believe the problem is caused by inserting spaces either side of `=` inside of the project.dependencies array affecting all [dependencies specified according to PEP 508](https://python-poetry.org/docs/dependency-specification/). 

Thanks for your time.
